# Generated by Django 5.2.6 on 2025-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_remove_user_preferred_contact_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
